DROP TABLE IF EXISTS party
CASCADE;

CREATE TABLE party
(
  id SERIAL PRIMARY KEY NOT NULL,
  name varchar(255) NOT NULL,
  access_code varchar(255) NOT NULL
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);