DROP TABLE IF EXISTS party_users
CASCADE;

CREATE TABLE party_users
(
  id SERIAL PRIMARY KEY NOT NULL,
  party_id INTEGER REFERENCES party(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);